development:
  db: 0
  host: localhost
  port: 6379
  namespace: pi_dev
  redis: redis://localhost:6379/0/pi_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: pi_test
  redis: redis://localhost:6379/1/pi_test
production:
  db: 0
  host: localhost
  port: 6379
  namespace: pi_prod
  redis: redis://localhost:6379/0/pi_prod
